---
title: "Subject Authentication"
output: pdf_document
---


```{r tread}
#Use RWeka method to read data from .arff files. Save the data into dataframes.
library(RWeka)
#get data by path
A11=paste("F:/wisdm-dataset/arff_files/phone/accel/data_160",1:9,'_accel_phone.arff',sep="")
A12=paste("F:/wisdm-dataset/arff_files/phone/accel/data_16",21:50,'_accel_phone.arff',sep="")
A1=c(A11,A12)
# Set variable name by paste function
N11=paste("data_160",1:9,'_accel_phone_origin',sep="")
N12=paste("data_16",10:39,'_accel_phone_origin',sep="")
N1=c(N11,N12)
for (i in 1:39){
  assign(N1[i],read.arff(file(description=A1[i])))
}


A21=paste("F:/wisdm-dataset/arff_files/phone/gyro/data_160",1:9,'_gyro_phone.arff',sep="")
A22=paste("F:/wisdm-dataset/arff_files/phone/gyro/data_16",21:50,'_gyro_phone.arff',sep="")
A2=c(A21,A22)
N21=paste("data_160",1:9,'_gyro_phone_origin',sep="")
N22=paste("data_16",10:39,'_gyro_phone_origin',sep="")
N2=c(N21,N22)
for (i in 1:39){
  assign(N2[i],read.arff(file(description=A2[i])))
}

A31=paste("F:/wisdm-dataset/arff_files/watch/accel/data_160",1:9,'_accel_watch.arff',sep="")
A32=paste("F:/wisdm-dataset/arff_files/watch/accel/data_16",21:50,'_accel_watch.arff',sep="")
A3=c(A31,A32)
N31=paste("data_160",1:9,'_accel_watch_origin',sep="")
N32=paste("data_16",10:39,'_accel_watch_origin',sep="")
N3=c(N31,N32)
for (i in 1:39){
  assign(N3[i],read.arff(file(description=A3[i])))
}

A41=paste("F:/wisdm-dataset/arff_files/watch/gyro/data_160",1:9,'_gyro_watch.arff',sep="")
A42=paste("F:/wisdm-dataset/arff_files/watch/gyro/data_16",21:50,'_gyro_watch.arff',sep="")
A4=c(A41,A42)
N41=paste("data_160",1:9,'_gyro_watch_origin',sep="")
N42=paste("data_16",10:39,'_gyro_watch_origin',sep="")
N4=c(N41,N42)
for (i in 1:39){
  assign(N4[i],read.arff(file(description=A4[i])))
}
```



```{r tdiv}
library(ISLR)
library(caret)
#Build the train data and test data for all the sensor data of all the subject(person)
set.seed(2)
#Build activity node list
ACTIVITY<-c('A','B','C','D','E','F','G','H','I','J','K','L','M','O','P','Q','R','S')
for (i in 1:9){
  #Use createDataPartition to divide data
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_accel_phone_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
  #Set a part train and test data set
    assign(paste("data_160",i,'_accel_phone_train',sep=""),get(paste("data_160",i,'_accel_phone_origin',sep=""))[sample_train,])
    assign(paste("data_160",i,'_accel_phone_test',sep=""),get(paste("data_160",i,'_accel_phone_origin',sep=""))[sample_train,])
#Set another part train and test data set
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_accel_phone_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_160",i,'_accel_phone_other',sep=""),get(paste("data_160",i,'_accel_phone_origin',sep=""))[sample_train,])

#Repeat what we done above in on a different file  
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_gyro_phone_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
    assign(paste("data_160",i,'_gyro_phone_train',sep=""),get(paste("data_160",i,'_gyro_phone_origin',sep=""))[sample_train,])
    assign(paste("data_160",i,'_gyro_phone_test',sep=""),get(paste("data_160",i,'_gyro_phone_origin',sep=""))[sample_train,])
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_gyro_phone_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_160",i,'_gyro_phone_other',sep=""),get(paste("data_160",i,'_gyro_phone_origin',sep=""))[sample_train,])

#Repeat what we done above in on a different file      
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_accel_watch_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
    assign(paste("data_160",i,'_accel_watch_train',sep=""),get(paste("data_160",i,'_accel_watch_origin',sep=""))[sample_train,])
    assign(paste("data_160",i,'_accel_watch_test',sep=""),get(paste("data_160",i,'_accel_watch_origin',sep=""))[sample_train,])
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_accel_watch_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_160",i,'_accel_watch_other',sep=""),get(paste("data_160",i,'_accel_watch_origin',sep=""))[sample_train,])

#Repeat what we done above in on a different file      
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_gyro_watch_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
    assign(paste("data_160",i,'_gyro_watch_train',sep=""),get(paste("data_160",i,'_gyro_watch_origin',sep=""))[sample_train,])
    assign(paste("data_160",i,'_gyro_watch_test',sep=""),get(paste("data_160",i,'_gyro_watch_origin',sep=""))[sample_train,])
    sample_train<-createDataPartition(y=get(paste("data_160",i,'_gyro_watch_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_160",i,'_gyro_watch_other',sep=""),get(paste("data_160",i,'_gyro_watch_origin',sep=""))[sample_train,])

}

#The follow loop repeat what we done in above loop in on a different condition  
for (i in 10:39){
  sample_train<-createDataPartition(y=get(paste("data_16",i,'_accel_phone_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
  assign(paste("data_16",i,'_accel_phone_train',sep=""),get(paste("data_16",i,'_accel_phone_origin',sep=""))[sample_train,])
  assign(paste("data_16",i,'_accel_phone_test',sep=""),get(paste("data_16",i,'_accel_phone_origin',sep=""))[sample_train,])
  sample_train<-createDataPartition(y=get(paste("data_16",i,'_accel_phone_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
  assign(paste("data_16",i,'_accel_phone_other',sep=""),get(paste("data_16",i,'_accel_phone_origin',sep=""))[sample_train,])

  
  sample_train<-createDataPartition(y=get(paste("data_16",i,'_gyro_phone_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
    assign(paste("data_16",i,'_gyro_phone_train',sep=""),get(paste("data_16",i,'_gyro_phone_origin',sep=""))[sample_train,])
    assign(paste("data_16",i,'_gyro_phone_test',sep=""),get(paste("data_16",i,'_gyro_phone_origin',sep=""))[sample_train,])
    sample_train<-createDataPartition(y=get(paste("data_16",i,'_gyro_phone_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_16",i,'_gyro_phone_other',sep=""),get(paste("data_16",i,'_gyro_phone_origin',sep=""))[sample_train,])

    
    sample_train<-createDataPartition(y=get(paste("data_16",i,'_accel_watch_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
    assign(paste("data_16",i,'_accel_watch_train',sep=""),get(paste("data_16",i,'_accel_watch_origin',sep=""))[sample_train,])
    assign(paste("data_16",i,'_accel_watch_test',sep=""),get(paste("data_16",i,'_accel_watch_origin',sep=""))[sample_train,])
    sample_train<-createDataPartition(y=get(paste("data_16",i,'_accel_watch_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_16",i,'_accel_watch_other',sep=""),get(paste("data_16",i,'_accel_watch_origin',sep=""))[sample_train,])

    
    sample_train<-createDataPartition(y=get(paste("data_16",i,'_gyro_watch_origin',sep=""))$ACTIVITY,p=0.5,list=FALSE)
    assign(paste("data_16",i,'_gyro_watch_train',sep=""),get(paste("data_16",i,'_gyro_watch_origin',sep=""))[sample_train,])
    assign(paste("data_16",i,'_gyro_watch_test',sep=""),get(paste("data_16",i,'_gyro_watch_origin',sep=""))[sample_train,])
    sample_train<-createDataPartition(y=get(paste("data_16",i,'_gyro_watch_origin',sep=""))$ACTIVITY,p=0.3,list=FALSE)
    assign(paste("data_16",i,'_gyro_watch_other',sep=""),get(paste("data_16",i,'_gyro_watch_origin',sep=""))[sample_train,])
    
}



```

```{r removeorigin}
#Remove the origin data got directly from file to save place.
rm(list =objects(pattern='origin')) 
```



```{r phone}
#Num is the index of person we select
Num=4
ACTIVITY<-c('A','B','C','D','E','F','G','H','I','J','K','L','M','O','P','Q','R','S')
tmp_begin<-data.frame()
for (i in ACTIVITY){
  a=1:39
  #Randomly select 9 other people to build train data and test data for the selected person, the data is from phone.
  #Build positive instance below
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_phone_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_accel_phone_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  
  
  
  #Build negetive instance below
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_accel_phone_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_accel_phone_train',sep=""),tmp_final)
  }
  
  
  #Repeat what we done above in on a different file 
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_phone_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_accel_phone_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""),tmp_final)
  }
  
  #Repeat what we done above in on a different file 
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_gyro_phone_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_gyro_phone_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_gyro_phone_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_gyro_phone_train',sep=""),tmp_final)
  }
  
  
  #Repeat what we done above in on a different file 
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_gyro_phone_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_gyro_phone_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""),tmp_final)
  }

  
}  

```


```{r watch}
#Randomly select 9 other people to build train data and test data for the selected person, the data is from watch. It's same as what we done with phone data 
ACTIVITY<-c('A','B','C','D','E','F','G','H','I','J','K','L','M','O','P','Q','R','S')
tmp_begin<-data.frame()
for (i in ACTIVITY){
  a=1:39  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_accel_watch_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_accel_watch_train',sep=""),tmp_final)
  }
  
  
  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""),tmp_final)
  }
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_gyro_watch_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_gyro_watch_train',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_gyro_watch_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_gyro_watch_train',sep=""),tmp_final)
  }
  
  
  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_gyro_watch_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  else{
    df=get(paste("data_16",Num,'_gyro_watch_test',sep=""))
    assign('tmp_begin',df[sample(nrow(df), 90), ])
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
  else{
    df=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), df[sample(nrow(df), 30), ]))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""),tmp_final)
  }
  
  
  
  
  
  

}  

```





```{r comb}
#Randomly select 9 other people to build train data and test data for the selected person, the data is from the combination of sensor data file. It's similar with what we done with phone data 
ACTIVITY<-c('A','B','C','D','E','F','G','H','I','J','K','L','M','O','P','Q','R','S')
tmp_begin<-data.frame()
for (i in ACTIVITY){
  a=1:39  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    #select two type of data
    df=get(paste("data_160",Num,'_accel_watch_train',sep=""))
    df2=get(paste("data_160",Num,'_accel_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    #combine them together
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_train',sep=""))
    df2=get(paste("data_16",Num,'_accel_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  #Build positiove instance above
  
  #Build negetive instance below
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_accel_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_accel_train',sep=""),tmp_final)
  }

  
  
  
  #Repeat what we done after build a  random_Num list above.
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_gyro_watch_train',sep=""))
    df2=get(paste("data_160",Num,'_gyro_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_gyro_watch_train',sep=""))
    df2=get(paste("data_16",Num,'_gyro_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_gyro_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""),tmp_final)
  }
  
  
  #Repeat what we done after build a  random_Num list above.
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_phone_train',sep=""))
    df2=get(paste("data_160",Num,'_gyro_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_phone_train',sep=""))
    df2=get(paste("data_16",Num,'_gyro_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_phone_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_phone_train',sep=""),tmp_final)
  }



  #Repeat what we done after build a  random_Num list above.
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_train',sep=""))
    df2=get(paste("data_160",Num,'_gyro_watch_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_train',sep=""))
    df2=get(paste("data_16",Num,'_gyro_watch_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_watch_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_watch_train',sep=""),tmp_final)
  }
  
  #Repeat what we done after build a  random_Num list above.
  #The code below is to build the data set which contains data from all the sensors.
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_train',sep=""))
    df2=get(paste("data_160",Num,'_gyro_watch_train',sep=""))
    df3=get(paste("data_160",Num,'_accel_phone_train',sep=""))
    df4=get(paste("data_160",Num,'_gyro_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    df3<-df3[sample(nrow(df3), 90), ]
    df4<-df4[sample(nrow(df4), 90), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_train',sep=""))
    df2=get(paste("data_16",Num,'_gyro_watch_train',sep=""))
    df3=get(paste("data_16",Num,'_accel_phone_train',sep=""))
    df4=get(paste("data_16",Num,'_gyro_phone_train',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    df3<-df3[sample(nrow(df3), 90), ]
    df4<-df4[sample(nrow(df4), 90), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df3=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df4=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    df3<-df3[sample(nrow(df3), 30), ]
    df4<-df4[sample(nrow(df4), 30), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df3=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df4=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    df3<-df3[sample(nrow(df3), 30), ]
    df4<-df4[sample(nrow(df4), 30), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_all_train',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_all_train',sep=""),tmp_final)
  }
  
  
  
  
  
  #The follow is building test data, which is similar with building the train data above.
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_test',sep=""))
    df2=get(paste("data_160",Num,'_accel_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_test',sep=""))
    df2=get(paste("data_16",Num,'_accel_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_accel_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_accel_test',sep=""),tmp_final)
  }
  
  
  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_gyro_watch_test',sep=""))
    df2=get(paste("data_160",Num,'_gyro_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_gyro_watch_test',sep=""))
    df2=get(paste("data_16",Num,'_gyro_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""),tmp_final)
  }
  
  
  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_phone_test',sep=""))
    df2=get(paste("data_160",Num,'_gyro_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_phone_test',sep=""))
    df2=get(paste("data_16",Num,'_gyro_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_phone_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_phone_test',sep=""),tmp_final)
  }



  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_test',sep=""))
    df2=get(paste("data_160",Num,'_gyro_watch_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_test',sep=""))
    df2=get(paste("data_16",Num,'_gyro_watch_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    tmp<-rbind.data.frame(df, df2)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    tmp<-rbind.data.frame(df, df2)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_watch_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_watch_test',sep=""),tmp_final)
  }
  
  random_Num=sample(a[a!=Num], 9, replace = FALSE)
  if (Num<10){
    df=get(paste("data_160",Num,'_accel_watch_test',sep=""))
    df2=get(paste("data_160",Num,'_gyro_watch_test',sep=""))
    df3=get(paste("data_160",Num,'_accel_phone_test',sep=""))
    df4=get(paste("data_160",Num,'_gyro_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    df3<-df3[sample(nrow(df3), 90), ]
    df4<-df4[sample(nrow(df4), 90), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)

    assign('tmp_begin',tmp)
  }
  else{
    df=get(paste("data_16",Num,'_accel_watch_test',sep=""))
    df2=get(paste("data_16",Num,'_gyro_watch_test',sep=""))
    df3=get(paste("data_16",Num,'_accel_phone_test',sep=""))
    df4=get(paste("data_16",Num,'_gyro_phone_test',sep=""))
    df<-df[sample(nrow(df), 90), ]
    df2<-df2[sample(nrow(df2), 90), ]
    df3<-df3[sample(nrow(df3), 90), ]
    df4<-df4[sample(nrow(df4), 90), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)

    assign('tmp_begin',tmp)
  }
  tmp_final<-tmp_begin
  tmp_final$class<-1L
  
  for (j in random_Num){
    if (j<10){
    df=get(paste("data_160",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_160",j,'_gyro_watch_other',sep=""))
    df3=get(paste("data_160",j,'_accel_phone_other',sep=""))
    df4=get(paste("data_160",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    df3<-df3[sample(nrow(df3), 30), ]
    df4<-df4[sample(nrow(df4), 30), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
  else{
    df=get(paste("data_16",j,'_accel_watch_other',sep=""))
    df2=get(paste("data_16",j,'_gyro_watch_other',sep=""))
    df3=get(paste("data_16",j,'_accel_phone_other',sep=""))
    df4=get(paste("data_16",j,'_gyro_phone_other',sep=""))
    df<-df[sample(nrow(df), 30), ]
    df2<-df2[sample(nrow(df2), 30), ]
    df3<-df3[sample(nrow(df3), 30), ]
    df4<-df4[sample(nrow(df4), 30), ]
    tmp<-rbind.data.frame(df, df2,df3,df4)
    tmp$class<-0L
    tmp_final<-data.frame(rbind((tmp_final), tmp))
  }
    
  }
  tmp_final$class<-as.factor(tmp_final$class)
  if (Num<10){
    assign(paste("data_160",Num,'_select_',i,'_all_test',sep=""),tmp_final)
  }
  else{
    assign(paste("data_16",Num,'_select_',i,'_all_test',sep=""),tmp_final)
  }
  
  
  
  
}  

```



```{r removeorigin}
#Do not need to run, just for clearing the wrong variable in environment.
#rm(list =objects(pattern='select')) 
```







```{r predict_knn}
##The block below is for the prediction of knn method. The accuracy of knn is saved in vectors tmpfinal_knn_1-tmpfinal_knn_9 and vector final_knn, which is the average of vectors tmpfinal_knn_1-tmpfinal_knn_9.
#Train the model in knn algorithm
library(ISLR)
library(caret)
library(C50)
library(pROC)
library(ROCR)
library(rpart)
library(e1071)
library(dplyr)
#Build the vectors to save the results
tmpfinal_knn_1<-c()
tmpfinal_knn_2<-c()
tmpfinal_knn_3<-c()
tmpfinal_knn_4<-c()
tmpfinal_knn_5<-c()
tmpfinal_knn_6<-c()
tmpfinal_knn_7<-c()
tmpfinal_knn_8<-c()
tmpfinal_knn_9<-c()
final_knn<-c()
if(Num<10){
for (i in ACTIVITY){
  #use caret package and knn method to train the model
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_phone_train',sep=""))))
  #Do perdiction use test data
assign(paste("p1_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))))
#Build confusionMatrix
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p1_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
#Get accuracy from confusionMatrix
tmpfinal_knn_1<-c(tmpfinal_knn_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
#Put avarage into final_knn vector
final_knn<-c(final_knn,sum(tmpfinal_knn_1)/18)
#All the parts below are similar to the part above

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p2_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p2_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_2<-c(tmpfinal_knn_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p3_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p3_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_3<-c(tmpfinal_knn_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p4_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p4_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_4<-c(tmpfinal_knn_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_4)/18)








}
if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_phone_train',sep=""))))
assign(paste("p1_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p1_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_knn_1<-c(tmp_final_knn_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmp_final_knn_1)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p2_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p2_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_knn_2<-c(tmp_final_knn_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmp_final_knn_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p3_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p3_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_knn_3<-c(tmp_final_knn_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmp_final_knn_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p4_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p4_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_knn_4<-c(tmp_final_knn_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmp_final_knn_4)/18)


}


tmpfinal_knn_5<-c()
tmpfinal_knn_6<-c()
tmpfinal_knn_7<-c()
tmpfinal_knn_8<-c()
tmpfinal_knn_9<-c()

if(Num<10){

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p5_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p5_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_5<-c(tmpfinal_knn_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p6_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p6_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_6<-c(tmpfinal_knn_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p7_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p7_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_7<-c(tmpfinal_knn_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p8_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p8_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_8<-c(tmpfinal_knn_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p9_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p9_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_9<-c(tmpfinal_knn_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_9)/18)





}



if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p5_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p5_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_5<-c(tmpfinal_knn_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p6_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p6_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_6<-c(tmpfinal_knn_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p7_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p7_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_7<-c(tmpfinal_knn_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p8_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p8_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_8<-c(tmpfinal_knn_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="knn",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p9_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p9_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_knn_9<-c(tmpfinal_knn_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_knn<-c(final_knn,sum(tmpfinal_knn_9)/18)


}
final_knn
```






```{r predict_cforest}
#The block below is for the prediction of random forest method. The accuracy of random forest is saved in vectors tmpfinal_cforest_1-tmpfinal_cforest_9 and vector final_cforest, which is the average of vectors tmpfinal_cforest_1-tmpfinal_cforest_9.
library(ISLR)
library(caret)
library(C50)
library(pROC)
library(ROCR)
library(rpart)
library(e1071)
library(dplyr)
tmpfinal_cforest_1<-c()
tmpfinal_cforest_2<-c()
tmpfinal_cforest_3<-c()
tmpfinal_cforest_4<-c()
tmpfinal_cforest_5<-c()
tmpfinal_cforest_6<-c()
tmpfinal_cforest_7<-c()
tmpfinal_cforest_8<-c()
tmpfinal_cforest_9<-c()
final_cforest<-c()
if(Num<10){
for (i in ACTIVITY){
  #use caret package and cforest method to train the model
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_phone_train',sep=""))))
  #Do perdiction use test data
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))))
#Build confusionMatrix
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
#Get accuracy from confusionMatrix
tmpfinal_cforest_1<-c(tmpfinal_cforest_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
  #Put avarage into final_cforest vector
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_1)/18)
#All the parts below are similar to the part above


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_2<-c(tmpfinal_cforest_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_3<-c(tmpfinal_cforest_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_4<-c(tmpfinal_cforest_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_4)/18)








}
if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_1<-c(tmp_final_cforest_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_1)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_2<-c(tmp_final_cforest_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_3<-c(tmp_final_cforest_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_4<-c(tmp_final_cforest_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_4)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_5<-c(tmp_final_cforest_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_6<-c(tmp_final_cforest_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_7<-c(tmp_final_cforest_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_8<-c(tmp_final_cforest_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_cforest_9<-c(tmp_final_cforest_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmp_final_cforest_9)/18)





}


tmpfinal_cforest_5<-c()
tmpfinal_cforest_6<-c()
tmpfinal_cforest_7<-c()
tmpfinal_cforest_8<-c()
tmpfinal_cforest_9<-c()

if(Num<10){

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_5<-c(tmpfinal_cforest_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_6<-c(tmpfinal_cforest_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_7<-c(tmpfinal_cforest_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_8<-c(tmpfinal_cforest_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_9<-c(tmpfinal_cforest_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_9)/18)





}



if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_5<-c(tmpfinal_cforest_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_6<-c(tmpfinal_cforest_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_7<-c(tmpfinal_cforest_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_8<-c(tmpfinal_cforest_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="cforest",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_cforest_9<-c(tmpfinal_cforest_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_cforest<-c(final_cforest,sum(tmpfinal_cforest_9)/18)


}
final_cforest
```













```{r predict_svmPoly, warning=FALSE}
#The block below is for the prediction of SVM method with Poly kernel. The accuracy of SVM is saved in vectors tmpfinal_svmLinear_1-tmpfinal_svmLinear_9 and vector final_svmLinear, which is the average of vectors tmpfinal_svmLinear_1-tmpfinal_svmLinear_9.
library(ISLR)
library(caret)
library(C50)
library(pROC)
library(ROCR)
library(rpart)
library(e1071)
library(dplyr)
tmpfinal_svmPoly_1<-c()
tmpfinal_svmPoly_2<-c()
tmpfinal_svmPoly_3<-c()
tmpfinal_svmPoly_4<-c()
tmpfinal_svmPoly_5<-c()
tmpfinal_svmPoly_6<-c()
tmpfinal_svmPoly_7<-c()
tmpfinal_svmPoly_8<-c()
tmpfinal_svmPoly_9<-c()
final_svmPoly<-c()
if(Num<10){
for (i in ACTIVITY){
  #use caret package and svmPoly method to train the model
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_phone_train',sep=""))))
  #Do perdiction use test data
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))))
#Build confusionMatrix
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
#Get accuracy from confusionMatrix
tmpfinal_svmPoly_1<-c(tmpfinal_svmPoly_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
  #Put avarage into final_svmPoly vector
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_1)/18)
#All the parts below are similar to the part above

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_2<-c(tmpfinal_svmPoly_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_3<-c(tmpfinal_svmPoly_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_4<-c(tmpfinal_svmPoly_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_4)/18)








}
if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_1<-c(tmp_final_svmPoly_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_1)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_2<-c(tmp_final_svmPoly_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_3<-c(tmp_final_svmPoly_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_4<-c(tmp_final_svmPoly_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_4)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_5<-c(tmp_final_svmPoly_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_6<-c(tmp_final_svmPoly_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_7<-c(tmp_final_svmPoly_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_8<-c(tmp_final_svmPoly_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmPoly_9<-c(tmp_final_svmPoly_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmp_final_svmPoly_9)/18)





}


tmpfinal_svmPoly_5<-c()
tmpfinal_svmPoly_6<-c()
tmpfinal_svmPoly_7<-c()
tmpfinal_svmPoly_8<-c()
tmpfinal_svmPoly_9<-c()

if(Num<10){

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_5<-c(tmpfinal_svmPoly_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_6<-c(tmpfinal_svmPoly_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_7<-c(tmpfinal_svmPoly_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_8<-c(tmpfinal_svmPoly_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_9<-c(tmpfinal_svmPoly_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_9)/18)





}



if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_5<-c(tmpfinal_svmPoly_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_6<-c(tmpfinal_svmPoly_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_7<-c(tmpfinal_svmPoly_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_8<-c(tmpfinal_svmPoly_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmPoly",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmPoly_9<-c(tmpfinal_svmPoly_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmPoly<-c(final_svmPoly,sum(tmpfinal_svmPoly_9)/18)


}
final_svmPoly
```




```{r predict_svmLinear}
#The block below is for the prediction of SVM method with linear kernel. The accuracy of SVM is saved in vectors tmpfinal_svmLinear_1-tmpfinal_svmLinear_9 and vector final_svmLinear, which is the average of vectors tmpfinal_svmLinear_1-tmpfinal_svmLinear_9. The only defference between the block and the block above is method.
library(ISLR)
library(caret)
library(C50)
library(pROC)
library(ROCR)
library(rpart)
library(e1071)
library(dplyr)
#define vectors to save the results
tmpfinal_svmLinear_1<-c()
tmpfinal_svmLinear_2<-c()
tmpfinal_svmLinear_3<-c()
tmpfinal_svmLinear_4<-c()
tmpfinal_svmLinear_5<-c()
tmpfinal_svmLinear_6<-c()
tmpfinal_svmLinear_7<-c()
tmpfinal_svmLinear_8<-c()
tmpfinal_svmLinear_9<-c()
final_svmLinear<-c()
if(Num<10){
for (i in ACTIVITY){
#use caret package and svmLinear method to train the model
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_1<-c(tmpfinal_svmLinear_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_1)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_2<-c(tmpfinal_svmLinear_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_3<-c(tmpfinal_svmLinear_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_4<-c(tmpfinal_svmLinear_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_4)/18)








}
if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_1<-c(tmp_final_svmLinear_1,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_1)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_2<-c(tmp_final_svmLinear_2,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_2)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_3<-c(tmp_final_svmLinear_3,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_3)/18)

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_4<-c(tmp_final_svmLinear_4,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_4)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_5<-c(tmp_final_svmLinear_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_6<-c(tmp_final_svmLinear_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_7<-c(tmp_final_svmLinear_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_8<-c(tmp_final_svmLinear_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmp_final_svmLinear_9<-c(tmp_final_svmLinear_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmp_final_svmLinear_9)/18)





}


tmpfinal_svmLinear_5<-c()
tmpfinal_svmLinear_6<-c()
tmpfinal_svmLinear_7<-c()
tmpfinal_svmLinear_8<-c()
tmpfinal_svmLinear_9<-c()

if(Num<10){

for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_5<-c(tmpfinal_svmLinear_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_6<-c(tmpfinal_svmLinear_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_7<-c(tmpfinal_svmLinear_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_8<-c(tmpfinal_svmLinear_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_160",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_160",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_9<-c(tmpfinal_svmLinear_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_9)/18)





}



if(Num>9){
  for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_phone_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_phone_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_5<-c(tmpfinal_svmLinear_5,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_5)/18)





for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_watch_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_watch_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_6<-c(tmpfinal_svmLinear_6,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_6)/18)



for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_accel_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_accel_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_7<-c(tmpfinal_svmLinear_7,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_7)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_gyro_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_gyro_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_8<-c(tmpfinal_svmLinear_8,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_8)/18)


for (i in ACTIVITY){
assign(paste("model",i,sep=""),train(class~.,method="svmLinear",metric="Accuracy",data=get(paste("data_16",Num,'_select_',i,'_all_train',sep=""))))
assign(paste("p_",i,sep=""),predict(get(paste("model",i,sep="")),get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))))
assign(paste("c_",i,sep=""),table(get(paste("data_16",Num,'_select_',i,'_all_test',sep=""))$class,get(paste("p_",i,sep="")),dnn = c('Actual','Predicted')))
assign(paste("m_",i,sep=""),confusionMatrix(get(paste("c_",i,sep=""))))
tmpfinal_svmLinear_9<-c(tmpfinal_svmLinear_9,as.numeric(get(paste("m_",i,sep=""))$overall[1]["Accuracy"]))  
  
}
final_svmLinear<-c(final_svmLinear,sum(tmpfinal_svmLinear_9)/18)


}
final_svmLinear
```



```{r build_table}
#Build the table we put in the paper for svmLinear. If we change the name of variables, we can get the table of other methods.
test_1<-matrix()
test_1<-rbind(as.matrix(t(tmpfinal_svmLinear_1)),as.matrix(t(tmpfinal_svmLinear_2)),as.matrix(t(tmpfinal_svmLinear_3)),as.matrix(t(tmpfinal_svmLinear_4)),as.matrix(t(tmpfinal_svmLinear_5)),as.matrix(t(tmpfinal_svmLinear_6)),as.matrix(t(tmpfinal_svmLinear_7)),as.matrix(t(tmpfinal_svmLinear_8)),as.matrix(t(tmpfinal_svmLinear_9)))
paper_table<-t(test_1)
paper_table
```